UnusedSites/Models/ErrorViewModel.cs
using System;

namespace UnusedSites.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UnusedSites/Models/Site.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


//Model for the site objects
namespace UnusedSites.Models{
    public class Site{
        public Site(int Id, string District, string Name, string Status, double NumAcres, int MonthLastUsed, int YearLastUsed, double PurchasePrice,
            double AppraisedValue, int MonthAppraised, int YearAppraised, double CurrentValue, string GradeLevel,string Changes, string Reason, string Approved)
        {
            this.Id = Id;
            this.District = District;
            this.Name = Name;
            this.Status = Status;
            this.NumAcres = NumAcres;
            this.MonthLastUsed = MonthLastUsed;
            this.YearLastUsed = YearLastUsed;
            this.PurchasePrice = PurchasePrice;
            this.AppraisedValue = AppraisedValue;
            this.MonthAppraised = MonthAppraised;
            this.YearAppraised = YearAppraised;
            this.CurrentValue = CurrentValue;
            this.GradeLevel = GradeLevel;
            this.Changes = Changes;
            this.Reason = Reason;
            this.Approved = Approved;
        } 
        public int Id{get;set;} 
        public string District{get;set;} 
        public string Name{get;set;} 
        public string Status{get;set;}
        public double NumAcres { get; set; }
        public int MonthLastUsed { get; set; }
        public int YearLastUsed { get; set; }
        public double PurchasePrice { get; set; }
        public double AppraisedValue { get; set; }
        public int MonthAppraised { get; set; }
        public int YearAppraised { get; set; }
        public double CurrentValue { get; set; }
        public string GradeLevel { get; set; }
        public string Changes { get; set; }
        public string Reason { get; set; }
        public string Approved {get; set;}

    }

    public class District
    {
        public District(int Id, string Name, string Contact_Salt, string Contact_FName, string Contact_LName,
            string Contact_PNumber, string Date_Sent, string Date_Received, string From424_Rec_Date, int Co_Code, 
            string Approved, List<Site> Sites)
        {
            this.Id = Id;
            this.Name = Name;
            this.Contact_Salt = Contact_Salt;
            this.Contact_FName = Contact_FName;
            this.Contact_LName = Contact_LName;
            this.Contact_PNumber = Contact_PNumber;
            this.Date_Sent = Date_Sent;
            this.Date_Received = Date_Received;
            this.From424_Rec_Date = From424_Rec_Date;
            this.Sites = Sites;
            this.Co_Code = Co_Code;
            this.Approved = Approved;
        }

        public District(int Id, string Name, string Contact_Salt, string Contact_FName, string Contact_LName,
            string Contact_PNumber, string Date_Sent, string Date_Received, string From424_Rec_Date, 
            int Co_Code, string Approved, int NumSites)
        {
            this.Id = Id;
            this.Name = Name;
            this.Contact_Salt = Contact_Salt;
            this.Contact_FName = Contact_FName;
            this.Contact_LName = Contact_LName;
            this.Contact_PNumber = Contact_PNumber;
            this.Date_Sent = Date_Sent;
            this.Date_Received = Date_Received;
            this.From424_Rec_Date = From424_Rec_Date;
            this.NumSites = NumSites;
            this.Co_Code = Co_Code;
            this.Dist_Code = Dist_Code;
            this.Approved = Approved;
        }
        public int Id { get; set; }
        public string Dist { get; set; }
        public string Name { get; set; }
        public string StatContact_Saltus { get; set; }
        public string Contact_Salt { get; set; }
        public string Contact_FName { get; set; }
        public string Contact_LName { get; set; }
        public string Contact_PNumber { get; set; }
        public string Date_Sent { get; set; }
        public string Date_Received { get; set; }
        public string From424_Rec_Date { get; set; }
        public int NumSites { get; set; }
        public int Co_Code { get; set; } 
        public int Dist_Code { get; set; } 
        public int Changes_Requested { get; set; } 
        public string Approved { get; set; } 

        public List<Site> Sites { get; set; }

    }
}

UnusedSites/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UnusedSites.Models;

namespace UnusedSites.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Home()
        {
            ViewData["Title"] = "Home";
            return View();
        }

        public IActionResult AccountHome()
        {
            ViewData["Title"] = "Account Home";
            return View();
        }

        public IActionResult AddSite()
        {
            ViewData["Title"] = "Add an Unused Site";
            return View();
        }

    }
}

UnusedSites/Controllers/UnusedSitesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UnusedSites.Models;
using UnusedSites.Data;

namespace UnusedSites.Controllers
{
    public class UnusedSitesController : Controller
    {
        public IActionResult Home()
        {
            ViewData["Title"] = "Home";
            return View();
        }
        public IActionResult Settings()
        {
            ViewData["Title"] = "Settings";
            return View();
        }

        public IActionResult AddSite()
        {
            ViewData["Title"] = "Add an Unused Site";
            return View();
        }

        public IActionResult Dashboard()
        {
            var districts =  SiteData.GetDistricts().ToList();
            ViewData["Title"] = "Dashboard";
            return View(districts);
        }

        public IActionResult District(int id)
        {
            var dist = SiteData.GetDistrict(id);
            ViewData["Title"] = "District";
            
            return View(dist);
        }

        public IActionResult Site(int id, int districtId)
        {
            var site = SiteData.GetSite(id).ToList();
            ViewData["Title"] = "DistrictSites";
            ViewData["districtId"] = districtId;

            return View(site);
        }
    }
}

UnusedSites/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="no-js ie9 oldie" lang="en"> <![endif]-->
<!--[if (gt IE 9)]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->
<head>
    <!--
        California State Template
        Version 5.0.2

        Based on Twitter Bootstrap
    -->
    <meta charset="utf-8">
    <title>@ViewData["Title"] - Unused Sites</title>
    <meta name="Author" content="State of California" />
    <meta name="Description" content="State of California" />
    <meta name="Keywords" content="California, government" />

    <!--Can be changed from Dev, Staging, Prod-->
    <environment inlcude="Development">
        <!-- Use highest compatibility mode -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- http://t.co/dKP3o1e -->
        <meta name="HandheldFriendly" content="True">
        <!-- for Blackberry, AvantGo -->
        <meta name="MobileOptimized" content="320">
        <!-- for Windows mobile -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
        <!-- Google Fonts -->
        <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700' rel='stylesheet' type='text/css'>

        <!--CSS Files-->
        <link rel="stylesheet" href="~/css/cagov.core.css" />
        <link rel="stylesheet" href="~/css/colorscheme-sacramento.css" />
        <link rel="stylesheet" href="~/site.css" />

        <!--JS Files-->
        <script type="text/javascript" src="~/js/libs/modernizr-3.6.0.min.js"></script>
        <script type="text/javascript" src="~/js/libs/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="~/js/libs/jquery-migrate-3.0.1.min.js"></script>
        <script type="text/javascript" src="~/js/cagov.core.js"></script>
        <script type="text/javascript" src="~/js/search.js"></script>

        <!-- selectivizr.com, emulates CSS3 pseudo-classes and attribute selectors in Internet Explorer 6-8 -->
        <!--[if (lt IE 9) & (!IEMobile)]>
        <script src="~/js/libs/selectivizr-min.js"></script>
        <![endif]-->
        <!-- For iPad 3-->
        <link rel="apple-touch-icon" sizes="144x144" href="~/images/template2014/apple-touch-icon-144x144.png" />
        <!-- For iPhone 4 -->
        <link rel="apple-touch-icon" sizes="114x114" href="~/images/template2014/apple-touch-icon-114x114.png">
        <!-- For iPad 1-->
        <link rel="apple-touch-icon" sizes="72x72" href="~/images/template2014/apple-touch-icon-72x72.png">
        <!-- For iPhone 3G, iPod Touch and Android -->
        <link rel="apple-touch-icon" href="~/images/template2014/apple-touch-icon-57x57.png">
        <!-- For Nokia -->
        <link rel="shortcut icon" href="~/images/template2014/apple-touch-icon-57x57.png">
        <!-- For everything else -->
        <link rel="shortcut icon" href="~/favicon.ico">
        <!-- Activate ClearType for Mobile IE -->
        <!--[if IE]>
        <meta http-equiv="cleartype" content="on">
        <![endif]-->
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="~/js/libs/html5shiv.min.js"></script>
          <script src="~/js/libs/respond.min.js"></script>
        <![endif]-->
    </environment>
</head>
<body>
    <header role="banner" id="header" class="global-header fixed">
        <div id="skip-to-content"><a href="#main-content">Skip to Main Content</a></div>
        <!-- Location Bar -->
        <div class="location-settings section section-standout collapse collapsed " id="locationSettings">
            <div class="container p-y">
                <button type="button" class="close" data-toggle="collapse" data-target="#locationSettings" aria-expanded="false" aria-controls="locationSettings" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <div class="form-group form-inline">
                    <label for="locationZipCode">Saving your location allows us to provide you with more relevant information.</label>
                    <input type="text" class="form-control" id="locationZipCode" placeholder="Zip Code">
                    <button type="button" class="btn btn-primary">Set Location</button>
                </div>
            </div>
        </div>

        <!-- Utility Header -->
        <div class="utility-header">
            <div class="container">
                <div class="group">
                    <div class="half">
                        <ul class="utility-links social-media-links">
                            <li><div class="header-cagov-logo"><a href="https://www.ca.gov/"><img src="~/images/Ca-Gov-Logo-Gold.svg" alt="CA.gov" /></a></div></li>
                            <li><a href="~/UnusedSites/Home"><span class="ca-gov-icon-home" aria-hidden="true"></span><span class="sr-only">Home</span></a></li>
                            <!--
        <li><a class="ca-gov-icon-facebook" title="Share via Facebook"><span class="sr-only">Facebook</span></a></li>
        <li><a class="ca-gov-icon-twitter" title="Share via Twitter"><span class="sr-only">Twitter</span></a></li>
        <li><a class="ca-gov-icon-google-plus" title="Share via Google+"><span class="sr-only">Google+</span></a></li>
        <li><a class="ca-gov-icon-email" title="Share via email"><span class="sr-only">Email</span></a></li>
    -->
                        </ul>
                    </div>
                    <div class="half settings-links p-t-sm">
                        <ul class="utility-links ">
                            <li><a href="">Contact Us</a></li>
                            <li><button class="btn btn-xs btn-primary" data-toggle="collapse" href="#siteSettings" aria-expanded="false" aria-controls="siteSettings"><span class="ca-gov-icon-gear" aria-hidden="true"></span> Settings</button></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!--  Settings Bar -->
        <div class="site-settings section section-standout collapse collapsed" role="alert" id="siteSettings">
            <div class="container  p-y">
                <button type="button" class="close" data-toggle="collapse" data-target="#siteSettings" aria-expanded="false" aria-controls="siteSettings" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div class="btn-group btn-group-justified-sm" role="group" aria-label="contrastMode">
                    <div class="btn-group"><button type="button" class="btn btn-standout disableHighContrastMode">Default</button></div>
                    <div class="btn-group"><button type="button" class="btn btn-standout enableHighContrastMode">High Contrast</button></div>
                </div>
                <div class="btn-group" role="group" aria-label="textSizeMode">
                    <div class="btn-group"><button type="button" class="btn btn-standout resetTextSize">Reset</button></div>
                    <div class="btn-group"><button type="button" class="btn btn-standout increaseTextSize"><span class="hidden-xs">Increase Font Size</span><span class="visible-xs">Font <small class="ca-gov-icon-plus-line"></small></span></button></div>
                    <div class="btn-group"><button type="button" class="btn btn-standout decreaseTextSize"><span class="hidden-xs">Decrease Font Size</span><span class="visible-xs">Font <small class="ca-gov-icon-minus-line"></small></span></button></div>
                </div>

            </div>
        </div>

        <!-- Branding -->
        <div class="branding">
            <div class="header-organization-banner"><a href="~/UnusedSites/Home"><img src="~/images/dgs_logo.jpg" alt="Organization Title" /></a></div>
        </div>

        <!-- mobile navigation controls -->
        <div class="mobile-controls">
            <span class="mobile-control-group mobile-header-icons">
                <!-- Add more mobile controls here. These will be on the right side of the mobile page header section -->
            </span>
            <div class="mobile-control-group main-nav-icons pull-right">
                <button class="mobile-control toggle-menu pull-right" aria-expanded="false" aria-controls="navigation"><span class="ca-gov-icon-menu" aria-hidden="true"></span><span class="sr-only">Menu</span></button>
                <button class="mobile-control toggle-search">
                    <span class="ca-gov-icon-search" aria-hidden="true"></span><span class="sr-only">Search</span>
                </button>
            </div>
        </div>


        <!--  Navigation -->
        <div class="navigation-search">
            <!-- Include Navigation -->
            <!-- Top Level Navigation Only -->
            <nav id="navigation" class="main-navigation singlelevelnav">
                <ul id="nav_list" class="top-level-nav">
                    <li class="home-link nav-item">
                        <a href="~/UnusedSites/Home" class="first-level-link"><span id="nav_home_container" class="ca-gov-icon-home" aria-hidden="true"></span>Home</a>
                    </li>

                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "AddSite" ? "active nav-item" : "nav-item")">
                        <a href="@Url.Action("AddSite", "UnusedSites")" class="first-level-link"><span class="ca-gov-icon-info-bubble" aria-hidden="true"></span>Add a Site</a>
                    </li>
                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "Dashboard" ? "active nav-item" : "nav-item")">
                        <a href="@Url.Action("Dashboard", "UnusedSites")" class="first-level-link"><span class="ca-gov-icon-flowchart" aria-hidden="true"></span>Dashboard</a>
                    </li>
                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "Settings" ? "active nav-item" : "nav-item")">
                        <a href="@Url.Action("Settings", "UnusedSites")" class="first-level-link"><span class="ca-gov-icon-gear" aria-hidden="true"></span>Settings</a>
                    </li>
                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "Contact" ? "active nav-item" : "nav-item")">
                        <a href="@Url.Action("Home", "UnusedSites")" class="first-level-link"><span class="ca-gov-icon-lightbulb" aria-hidden="true"></span>Home</a>
                    </li>

                    @*<li class="nav-item" id="nav-item-search">
            <a href="javascript:;" class="first-level-link"><span class="ca-gov-icon-search" aria-hidden="true"></span>Search</a>
        </li>*@
                </ul>
            </nav>
            <div id="head-search" class="search-container">
                <script type="text/javascript">
                    var cx = '001779225245372747843:9s-idxui5pk';// Step 7: Update this value with your search engine unique ID. Submit a request to the CDT Service Desk if you don't already know your unique search engine ID.
                    var gcse = document.createElement('script');
                    gcse.type = 'text/javascript';
                    gcse.async = true;
                    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
                    var s = document.getElementsByTagName('script');
                    s[s.length - 1].parentNode.insertBefore(gcse, s[s.length - 1]);
                </script>
                <!-- Google Custom Search -->
                <gcse:searchbox-only resultsUrl="~/Home/serp" enableAutoComplete="true"></gcse:searchbox-only>
            </div>
        </div>
    </header>
    <div class="header-decoration"></div>
    <div id="main-content" class="main-content">
        <div class="section">
            @RenderBody()
        </div>
    </div>

    <!-- Global Footer -->
    <footer id="footer" class="global-footer">
        <div class="container">
            <div class="row">
                <div class="three-quarters">
                    <ul class="footer-links">
                        <li><a href="#skip-to-content">Back to Top</a></li>
                        <!--
    <li><a href="/">Conditions of Use</a></li>
    <li><a href="/">Privacy Policy</a></li>
    <li><a href="/">Accessibility</a></li>
    <li><a href="/">Contact Us</a></li>
    -->
                    </ul>
                </div>
                <div class="quarter text-right">
                    <!--
                    <ul class="socialsharer-container">
                        <li><a href="https://www.flickr.com/groups/californiagovernment"><span class="ca-gov-icon-flickr" aria-hidden="true"></span><span class="sr-only">Flickr</span></a></li>
                        <li><a href="https://www.pinterest.com/cagovernment/"><span class="ca-gov-icon-pinterest" aria-hidden="true"></span><span class="sr-only">Pinterest</span></a></li>
                        <li><a href="https://twitter.com/cagovernment"><span class="ca-gov-icon-twitter" aria-hidden="true"></span><span class="sr-only">Twitter</span></a></li>
                        <li><a href="https://www.youtube.com/user/californiagovernment"><span class="ca-gov-icon-youtube" aria-hidden="true"></span><span class="sr-only">YouTube</span></a></li>
                    </ul>
                        -->
                </div>
            </div>
        </div>
        <!-- Copyright Statement -->
        <div class="copyright">
            <div class="container">
                Copyright &copy;
                <script>document.write(new Date().getFullYear())</script> State of California
            </div>
        </div>
    </footer>
<!---end-->

</body>
</html>

UnusedSites/Views/UnusedSites/Dashboard.cshtml
@model List<UnusedSites.Models.District>
<div class="group">
    <aside class="featured-narrative text-center">
        <h1>Unused Sites Program</h1>
    </aside>
</div>
<br />
<div class="btn-row text-left">
    <button onclick="location.href='@Url.Action("AddSite", "UnusedSites")';return false;" alt="Add a new Unused Site" class="btn btn-primary">ADD NEW UNUSED SITE</button>
</div>
<div class="row">
    <div class="quarter offset-three-quarters">
        <div class="form-group">
            <label for="filterDistrict" class="form-control-label"> Filter Districts</label>
            <input type="text" class="form-control" id="filterDistrict" placeholder="Filter Districts">
        </div>
    </div>
</div>
@*<div class="group">
    <div class="row">
        <div class="quarter">
                
        </div>
        <div class="quarter">
            <label class="select">
                <select name="email" id="email">
                    <option selected>Filter By Year</option>
                    <option>Generate from DB!</option>
                    <option value="2001">2001</option>
                    <option value="2002">2002</option>
                </select>
            </label>
        </div>
        <div class="quarter">
            <div class="input-group" id="districtCodeSort">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="ca-gov-icon-search-right"></i></span>
                </div>
                <input type="text" class="form-control" id="validationFirstName" placeholder="District Code" value="Search By District Code">
            </div>
        </div>
        <div class="quarter offset-half">
            <div class="form-group">
                <input type="text" class="form-control" id="filterDistrict" placeholder="Filter Unused Sites">
            </div>
            <div class="input-group" id="districtCodeSort">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="ca-gov-icon-search-right"></i></span>
                </div>
                <input type="text" class="form-control" id="validationFirstName" placeholder="School Name" value="Search By School Name">
            </div>
        </div>
    </div>
</div>*@
<br />

<div class="container">
</div>
<div class="group">
    <div class="row">
        <div class="half text-left">
        </div>
    </div>
</div>

    <div class="table-responsive">
        <table class="table table-default">
            <thead>
                <tr>
                    <th>DISTRICT NAME</th>
                    <th>COUNTY CODE</th>
                    <th>DISTRICT CODE</th>
                    <th>CONTACT NAME</th>
                    <th>CONTACT NUMBER</th>
                    <th># OF SITES</th>
                    <th>APPROVED</th>
                    @*<th>ID</th>
                    <th>District</th>
                    <th>CONTACT</th>
                    <th>PHONE NUMBER</th>
                    <th>DATE SENT</th> 
                    <th>DATE RECIEVED</th>
                    <th>DATE APPROVED</th>
                    <th>424 FORM DATE RECIEVED</th>
                    <th>NUMBER OF SITES</th>*@
                </tr>
            </thead>
            <tbody id="dashboardUnusedSites">
                @foreach(var item in Model){
                <tr>
                    <td>
                        @Html.ActionLink(item.Name, "District", "UnusedSites", new {id = item.Id })
                    </td>
                    <td>
                        @item.Co_Code
                    </td>
                    <td>
                        @item.Id
                    </td>
                    <td>
                        @item.Contact_FName
                        @item.Contact_LName
                    </td>
                    <td>
                        @item.Contact_PNumber
                    </td>
                    <td>
                        @item.NumSites
                    </td>
                    <td>
                        @item.Approved
                    </td>

                    @*
                    <td>
                        @item.Id
                    </td>
                    <td>
                        @Html.ActionLink(item.Name, "District", "UnusedSites", new {id = item.Id })
                    </td>
                    <td>
                        @item.Contact_Salt
                        @Html.ActionLink(item.Name, "Site", "UnusedSites", new {id = item.Name})
                        @item.Contact_FName
                        @item.Contact_LName
                    </td>
                    <td>
                        @item.Contact_PNumber
                    </td>
                    <td>
                        @item.Date_Sent
                    </td>
                    <td>
                        @item.Date_Received
                    </td>
                    <td>
                        @item.Date_Approved
                    </td>
                    <td>
                        @item.From424_Rec_Date
                    </td>
                    <td>
                        @item.NumSites
                    </td>
                    *@
                </tr>
                }
            </tbody>
        </table>
    </div>
<script>
    $(document).ready(function () {
        $("#filterDistrict").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#dashboardUnusedSites tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>

UnusedSites/Views/UnusedSites/District.cshtml
@model UnusedSites.Models.District
<div class="group">
    <aside class="featured-narrative text-center">
        <h1>@Model.Name</h1>
    </aside>
</div>
<div class="btn-row text-left">
    <button onclick="location.href='@Url.Action("AddSite", "UnusedSites")';return false;" class="btn btn-primary">ADD NEW UNUSED SITE</button>
    <button class="btn btn-primary">EDIT DISTRICT</button>
    <button onclick="location.href='@Url.Action("Dashboard", "UnusedSites")';return false;" class="btn btn-primary">BACK</button>
</div>
<div class="row">
    <div class="half">
        <p>
            <b>ID:</b> @Model.Id<br />
            <b>Name:</b> @Model.Name<br />
            <b>Contact:</b> @Model.Contact_Salt @Model.Contact_FName @Model.Contact_LName<br />
            <b>Contact Phone Number:</b> @Model.Contact_PNumber<br />
            <b>Date Sent:</b> @Model.Date_Sent<br />
            <b>Date Received:</b> @Model.Date_Received
        </p>
    </div>
    <div class="quarter offset-quarter">
        <div class="form-group">
            <label for="filterDistrict" class="form-control-label"> Filter Unused Sites</label>
            <input type="text" class="form-control" id="filterDistrict" placeholder="Filter Unused Sites">
        </div>
    </div>
</div>
@*<div class="group">
        <div class="btn-row">
            <input style="float: right;"type="text" placeholder="Search..." />
        </div>
    </div>*@

<div class="group">
    <div class="table-responsive">
        @*<ul style="list-style-type: none; font-size: 20px; padding: 0;">
            <li><b>ID:</b> @Model.Id</li>
            <li><b>Name:</b> @Model.Name</li>
            <li><b>Contact:</b> @Model.Contact_Salt @Model.Contact_FName @Model.Contact_LName</li>
            <li><b>Contact Phone Number:</b> @Model.Contact_PNumber</li>
            <li><b>Date Sent:</b> @Model.Date_Sent</li>
            <li><b>Date Received:</b> @Model.Date_Received</li>
        </ul>*@
        <table class="table table-default">
            <thead>
                <tr>
                    <th>SITE NAME</th>
                    <th>SITE CODE</th>
                    <th>STATUS</th>
                    <th>REASON</th>
                    <th>GRADE LEVEL</th>
                    <th>LAST YEAR USED</th>
                    <th>EFFECTIVE FEE</th>
                    <th>APPROVED</th>
                    @*<th>ID</th>
                    <th>SITE NAME</th>
                    <th>STATUS</th>
                    <th>REASON</th>
                    <th>YEAR LAST USED</th>
                    <th>CURRENT VALUE</th>
                    <th>GRADE LEVEL</th>
                    <th>CHANGES</th>
                    <th>APPROVED</th>*@
                </tr>
            </thead>
            <tbody id="districtUnusedSites">
                @foreach (var item in Model.Sites)
                {
                    <tr>
                        <td>
                            @Html.ActionLink(item.Name, "Site", "UnusedSites", new { id = item.Id, districtId = Model.Id })
                        </td>
                        <td>
                            @item.Id
                        </td>
                        <td>
                            @item.Status
                        </td>
                        <td>
                            @item.Reason
                        </td>
                        <td>
                            @item.GradeLevel
                        </td>
                        <td>
                            @item.YearLastUsed
                        </td>
                        <td>
                            $@item.CurrentValue
                        </td>
                        <td>
                            @item.Approved
                        </td>
                        @*<td>
                            @item.Id
                        </td>
                        <td>
                            @Html.ActionLink(item.Name, "Site", "UnusedSites", new { id = item.Id, districtId = Model.Id })
                        </td>
                        <td>
                            @item.Status
                        </td>
                        <td>
                            @item.Reason
                        </td>
                        <td>
                            @item.YearLastUsed
                        </td>
                        <td>
                            $@item.CurrentValue
                        </td>
                        <td>
                            @item.GradeLevel
                        </td>
                        <td>
                            @item.Changes
                        </td>
                        <td>
                            @item.Approved
                        </td>*@
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#filterDistrict").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#districtUnusedSites tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>